// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR4VFapn-txilsoR6eyyk3-s3E-hcz9ww',
    appId: '1:664838630073:web:8f84e735471a1c20714968',
    messagingSenderId: '664838630073',
    projectId: 'chat-app-537de',
    authDomain: 'chat-app-537de.firebaseapp.com',
    storageBucket: 'chat-app-537de.appspot.com',
    measurementId: 'G-QN2E55LVH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvESRIjtnaas_TTY9kMJ6udBiElyMTrk8',
    appId: '1:664838630073:android:21e8761d33ea2f00714968',
    messagingSenderId: '664838630073',
    projectId: 'chat-app-537de',
    storageBucket: 'chat-app-537de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtAmq_1DX1p3RD0IMU4f0cICfN0fLySCo',
    appId: '1:664838630073:ios:a5d2490095612923714968',
    messagingSenderId: '664838630073',
    projectId: 'chat-app-537de',
    storageBucket: 'chat-app-537de.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
